#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

# Copy the original hosts file to a temporary location
cp /etc/hosts ~/hosts.new

# Modify the hosts file with the desired entries
echo "127.0.0.2         localhost" > ~/hosts.new
echo "8.8.8.8           facebook.com" >> ~/hosts.new

# Copy the modified hosts file back to /etc/hosts with sudo
sudo cp -f ~/hosts.new /etc/hosts

echo "Hosts file configured successfully."
