#!/usr/bin/env bash

#script that displays all active IPv4 IPs on the machine it’s executed on.

#!/usr/bin/env bash

#script that displays all active IPv4 IPs on the machine it’s executed on.

ifconfig | grep -oP '\binet\saddr:([0-9]{1,3}\.){3}[0-9]{1,3}\b' | cut -d ' ' -f 2
