#!/usr/bin/env bash
#If you’re running this script on a machine that you’ll continue to use,
#be sure to revert localhost to 127.0.0.1. Otherwise,
#a lot of things will stop working!

# Check if the script is running with sudo
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with sudo:"
    echo "sudo $0"
    exit 1
fi

# Revert to the original hosts file
cp /etc/hosts.original /etc/hosts

echo "Hosts file reverted to the original configuration."
